### ISSUE TITLE
Lack of the mraa_init call in these example codes

### ISSUE THREAD

**Issue by sdssly** [intel-iot-devkit/mraa#175]
Such as the hellomraa.c, helloedison.c, the mraa_init call is needed

**Comment by michael-ring** [comment]
Hmm, I guess it it more the opposite, mraa_init is called when the .so is initialized, when you check the return code you will see that it says MRAA_ALREADY_INITIALIZED, so those calls are obsolete.

**Comment by arfoll** [comment]
Hi @sdssly, the mraa_init() call is entirely optional (unless your libc is compiled without CTORS). The reason it's not in the examples is because it's really just a safety check and our examples - hopefully obviously - lack alot of error checking in the hope to be clear and to generate decent *interesting* tags in our doxygen docs. Note documentation on mraa_init() hopefully makes this clear - http://iotdk.intel.com/docs/master/mraa/common_8h.html#a1ebdf9bc53d7031e41632b15a17019d3

**Comment by michael-ring** [comment]
Well, documentation seems a little outdated, is says:

Anything but MRAA_SUCCESS should be considered a critical failure

When you call mraa_init in application code you get 

MRAA_ERROR_PLATFORM_ALREADY_INITIALISED

which is not really a critical failure but more a hint that init was already done for you automagically

**Comment by arfoll** [comment]
Indeed I re-read that too quickly - fixed documentation with e03eec3ce16fe0a52bc709e259f5b2319739fdd4

**Comment by sdssly** [comment]
Thanks for your update! I just found the root cause. For some reason, my local build defined the SWIG. So the mraa_init is not a auto call. 

I would like to know when we will define the SWIG? why use the SWIG?

**Comment by arfoll** [comment]
When you do a build the swig modules it uses the %init {} prop in the interface file rather than the constructor https://github.com/intel-iot-devkit/mraa/blob/master/src/mraa.i#L27

How are you building? And why is SWIG defined? It should not be defined when building the C/C++ library only when building the SWIG interface wrapper files.
