### ISSUE TITLE
Any bluetooth examples?

### ISSUE THREAD

**Issue by rclai** [intel-iot-devkit/mraa#323]
Was wondering if there was a way to programmatically work with the bluetooth module?

I am a bit new to IoT tech.

**Comment by alext-mkrs** [comment]
You probably mean Edison here, right?

Generally speaking, mraa is not targeting this, because (IMHO, @arfoll would be authoritative here) there's not much can be done to make it simpler (given all those profiles you have there), which is mraa's main goal. To use bluetooth, you could use standard linux BT programming approaches, involving BlueZ most probably.

Though while typing this I started to think that actually be an interesting idea to try and implement something like this, maybe in some limited fashion, but still that could make BT more accessible :smiley:

**Comment by rclai** [comment]
Yes, the Edison. I actually found another solution by using [this solution](https://github.com/bbx10/node-nRF8001), which depends on Noble. So I'm closing now.
