### ISSUE TITLE
[Edison Arduino] Illegal arguments for construction of _exports_Pwm on IO 10/11 (PWM swizzler)

### ISSUE THREAD

**Issue by rwaldron** [intel-iot-devkit/mraa#52]
Environment: 

```
root@blurr:~# cat /etc/version && node -e 'console.log(require("mraa").getVersion());' && node -v
edison-rel1-maint-weekly_build_16_2014-10-14_14-56-19
v0.5.4-2-gffdd828
v0.10.28
```

Error: 
```
root@blurr:~# node
> var m = require("mraa")
undefined
> var p = new m.Pwm(11)
Error: Illegal arguments for construction of _exports_Pwm
    at repl:1:9
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

(blurr => edison)

**Comment by alext-mkrs** [comment]
FWIW, I would vote for just closing this one - we state clearly in the docs that we only support PWM on default swizzler pins and anything else (e.g. allowing to use 10 and 11) would indeed require something outside of the library control - a user action on swizzler config - which IMHO is more dangerous than beneficial.

Same as right now someone could be confused by not being able to drive PWM on pins 10 and 11, they would be confused by GPIO pins being activated unexpectedly. And as long as the former could only cause frustration (until the documentation is read), the latter could cause some actual damage, that's why I believe the current approach is safer thus better.

**Comment by alext-mkrs** [comment]
@arfoll, do you think we can close this one, IMHO it's quite straightforward?

@rwaldron, any additonal suggestions on how we could make it clear, now that some time passed (I see just one mention so far, so looks like there weren't too many problems with that)?

**Comment by rwaldron** [comment]
There is nothing to be done in software space.
