### ISSUE TITLE
how to install then on the target if build-ed with yocto cross sdk?

### ISSUE THREAD

**Issue by mgiaco** [intel-iot-devkit/mraa#766]
Hi, I followed the guide for building mraa via yocto sdk. It seems to work but after the build what is the right way to get those build on the target - sorry for the maybe silly question.

**Comment by mgiaco** [comment]
So no one uses yocto?
I also tried the intel iot recipes but i looks unmaintained for me?

**Comment by arfoll** [comment]
Many do it, but our recipes are a bit of an unmaintained mess all over the place, we don't have a good central place. The best I know of currently is https://github.com/intel/intel-iot-refkit/tree/master/meta-refkit-core/recipes-sensors.

**Comment by mgiaco** [comment]
Okay many thanks I will try that - but if i compile it via the cross sdk - how can i install it on the target then?  
So okay I can copy and paste the *.so and py files at the right place. But is there a way to install them after build on the cross sdk?

**Comment by arfoll** [comment]
I'm not sure which cross SDK you are referring to. If you create your own packages for your device you really have to create a cross SDK for your device too. That's the "proper" way of doing things. Obviously copying binaries works too :)

**Comment by alext-mkrs** [comment]
I guess @mgiaco is asking about a scenario where mraa is being built on the host by using cross SDK generated by Yocto, is that correct? If so, that's a bit unnatural way of doing that, but generally yes, you need to manually copy generated files into proper places, there's no "normal" of installing files built like that, like "make install" - as this way of building doesn't have the means of installing built binaries.

The files are, OTMH: main .so, python, nodejs, java bindings (whichever of those you build). Specific locations depend on details of your target.

**Comment by mgiaco** [comment]
@alext-mkrs  Hey - yes that was my question. No I have integrated all the build tools in the yocto image and build mraa on the device but for production I would like to have a small image. So I hope I will find a working recipe.

Or what is the natural way?

**Comment by alext-mkrs** [comment]
I see. So having Yocto and embedded system in the context, there are three basic ways of building software for your target (board):
1. Build on host, using Yocto itself (not the SDK). This is typically used for building OS images or additional SW for it. SW typically gets packaged to something used by the OS image (ipk, rpm, deb). This depends on the settings, but typically some form of package management is enabled everywhere. This would be the way I'd recommend you to follow to get mraa built.
1. Build on host, using the SDK, generated by Yocto for the OS image you've built. This is generally a way for building your "user" or "functional" applications you want to run on top of your target's OS+library set. Building mraa (or other libraries, to that matter) may be more difficult at least because of the fact there's no packaging when using this one. Then, there's e.g. no direct support for CMake-based projects, unlike in the Yocto way above. So technically you can do that, practically I'd not recommend it for mraa building.
1. Building on the target. You tried that already. Simplest of all three, but can be slow (depending on the target) and may require target configuration (installing additional headers, libraries).

All in all, I'd recommend you to either build on target, or use the Yocto mraa recipe @arfoll referred to in your other issue and build via Yocto. Using SDK would be my last resort of all three.

**Comment by mgiaco** [comment]
Okay many thanks I will try that.
